//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace machidesignAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Events()
        {
            this.MachiarukiDatas = new HashSet<MachiarukiDatas>();
            this.Machiarukis = new HashSet<Machiarukis>();
        }
    
        public long EventsId { get; set; }
        public System.DateTime InsDate { get; set; }
        public System.DateTime UpdDate { get; set; }
        public string InsAccountId { get; set; }
        public string UpdAccountId { get; set; }
        public string YukoFlg { get; set; }
        public string EventName { get; set; }
        public System.DateTime KaisaiDate_Start { get; set; }
        public string KaisaiTime_Start { get; set; }
        public System.DateTime KaisaiDate_End { get; set; }
        public string KaisaiTime_End { get; set; }
        public string Kaijo { get; set; }
        public string KaijoAdr { get; set; }
        public string KaijoUrl { get; set; }
        public string EventDescription { get; set; }
        public string EventDetails { get; set; }
        public int MaxNinzu { get; set; }
        public decimal Kaihi { get; set; }
        public string KaihiBiko { get; set; }
    
        public virtual Groups Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachiarukiDatas> MachiarukiDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machiarukis> Machiarukis { get; set; }
    }
}
