//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace machidesignAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class machidesignEntities : DbContext
    {
        public machidesignEntities()
            : base("name=machidesignEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Jichitais> Jichitais { get; set; }
        public virtual DbSet<MachiarukiDatas> MachiarukiDatas { get; set; }
        public virtual DbSet<Machiarukis> Machiarukis { get; set; }
    }
}
